spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: stock
    password: stock
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
security:
  jwt:
    secret: myverysecuresecretkeymyverysecuresecretkey12345
    expiration: 86400000
server:
  port: 8080
